steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-chatgpt-bot/gpt-app/image:${_BUILD_ID}', '.']
images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/slack-chatgpt-bot/gpt-app/image:${_BUILD_ID}'